name: build-deploy-azure-app
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Install dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: GitHub NuGet auth
        run: dotnet nuget add source "https://nuget.pkg.github.com/YuraChernii/index.json" --name 'mik373737373737@gmail.com' --username az --password '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'
      - name: Restore Nuget packages of api
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build
      - name: Publish
        run: dotnet publish ./src/SecureResource.Service.IdentityServer.Api/SecureResource.Service.IdentityServer.csproj -c Release -o website
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: website/**
          if-no-files-found: error
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: app
          path: app
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: SecireResourceIdentityServer-App
          package: app
      - name: Logout from Azure
        run: az logout 